### ISSUE TITLE
Write a readme text

### ISSUE THREAD

**Issue by svennoreillie** [svennoreillie/ACE_Informatica_DatumOpdracht1#5]
Be artistic !

**Comment by geertvw** [comment]
Test 1
Gandalf

**Comment by geertvw** [comment]
***DRAFT***
**Author:Gandalf**
GITHUB README TEXT

Requested format: .txt or .rtf?

TO DECIDE

What do we want to see included in the readme.txt of our project?
- History
- Read this before using the code
- Installation instructions
- How to contact the developers
- Anything else?
![dilbert_projects_dt150908](https://cloud.githubusercontent.com/assets/14618291/10087929/63c3b2ec-6317-11e5-89de-1cd33cfc54bb.gif)

***Cartoon added as a test of adding pictures***
